image: docker:latest

# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay

services:
- docker:dind

before_script:
- docker info

stages:
  - build
#  - test
  - deploy


job1:
  stage: build
  script:
  - docker build -t mmumshad/ansible-playable .


#job2:
#  stage: test
#  script:
#  - docker run  --name afs-mongo -d mongo
#  - docker run -it -p 9522:22 -p 9500:9000 -p 3500:3000 -p 3502:3002 -p 3501:3001 --link afs-mongo:db  ansible-playable-test

job2:
  stage: deploy
  script:
  - docker push mmumshad/ansible-playable
