language: node_js
node_js:
  - 8
matrix:
  fast_finish: true
  allow_failures:
    - node_js: 5.12.0
before_script:
  - npm install -g gulp-cli node-gyp 
services: mongodb
cache:
  directories:
    - node_modules
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
